pipeline {
   environment {
     REGISTRY_ENDPOINT = "https://binblee/v2/"
     IMAGE_WITH_TAG = "binblee/springboot-helm-chart"
     REGISTRY_CERTS = "registry"
   }
  agent {
    node {
      label 'master'
    }

  }
  stages {
    stage('Build') {
      steps {
        sh 'mvn package'
      }
    }
    stage('Test') {
      steps {
        sh 'mvn test '
      }
    }
    stage('Image Build&Publish') {
      steps {
        echo 'Build Images'
        script {
           sh 'docker build -t ${IMAGE}:$TAG .'
            sh 'docker push ${IMAGE_WITH_TAG}'
           }

      }
    }
  }
}
